

export default [
  bases=[
    {
      id:1,
      image:,
      description:"base marca mac, covertura media, excelente pigmentacion",
      price:15000
    },
    {
      id:2,
      image:,
      description:"Base de maquillaje líquido Samy enriquecida con extracto de pepino, aloe vera, vitamina E y coenzima Q10",
      price:37800
    },
    {
      id:3,
      image:,
      description:"Base líquida Vogue, que dura hasta 11h, controla el brillo, cubre imperfecciones y contiene filtros solares",
      price:47560,

    },
    {
      id:4,
      image:,
      description:" Base líquida colorfix que dura hasta 11h, controla el brillo, cubre imperfecciones y contiene filtros solares ",
      price:22589
    },
    {
      id:5,
      image:,
      description:"Base mate de Loreal con covertura media, contiene extractos de arroz y vitaminas para tu piel",
      price:2790
    },
    {
      id:6,
      image:,
      description:"Base hidratante marca Atenea , buena covertura,con minerales y extractos que ayudan a tu piel.",
      price:25600
    },
    {
      id:7,
      image:
      description:"La base de la línea FEELS  Ruby Rose ,proporciona una cobertura alta, ideal para corregir imperfecciones e igualar el tono de la piel, sin dejar una apariencia pesada. ",
      price:8756
    },
    {
      id:8,
      image:,
      description:"Base truly La Colors ,La base Truly Matte tiene una fórmula de larga duración además de ser una base de alta pigmentación brindando un tono uniforme a tu rostro libre de imperfecciones, su acabado mate es muy similar al de aplicar polvo.",
      price:11679
    },
    {
      id:9,
      image:,
      description:"La base perfecta debe igualar el tono y la textura de tu piel.",
      price:2569
    },
    {
      id:10,
      image:,
      description:"Base conceal + perfect ,diseñada para cubrir desde el enrojecimiento y otras imperfecciones de la piel hasta manchas profundas sin dejar de ser ligera y además es resistente al agua",
      price:11256
    }

  ],
  eyelashes=[
    {
      id:1,
      image:,
      description:"Pestañina Maybelline Colossal Volum Express Lavable",
      price:3000
    },
    {
      id:2,
      image:,
      description:"Pestañina natura , múltiples beneficios. Logra una personalización de acabado desde uno más natural hasta uno con mayor volumen, más alargamiento, más curvatura sin grumos y más definición y fórmula de alta performance. ",
      price:13800
    },
    {
      id:3,
      image:,
      description:"Esta increíble Pestañina tiene un MEGA cepillo para que tus pestañas se vean grandes, grandes y más grandes, como las pestañas de una hermosa muñeca.",
      price:7560,

    },
    {
      id:4,
      image:,
      description:"Pestañina loreal ,Sin escamas, no hay manchas, ni grumos. Según estudio las mujeres estuvieron de acuerdo: 91% vieron pestañas intensas y volumizadas",
      price:23579
    },
    {
      id:5,
      image:,
      description:"la pestañina Mac, tiene una fórmula batida y liviana de M·A·C da volumen, alarga y riza las pestañas mientras las acondiciona para mayor suavidad y flexibilidad.",
      price:9790
    },
    {
      id:6,
      image:,
      description:"la pestañina ruby rose, fue creada especialmente para definir y alargar las pestañas, con su exclusivo aplicador proporcionará un acabado sorprendente y natural",
      price:5600
    },
    {
      id:7,
      image:,
      description:"Pestaniña Transparenre Nailen A base de ingredientes naturales.",
      price:8756
    },
    {
      id:8,
      image:,
      description:"la pestañina vitu,da  un aspecto de pestañas con volumen y definidas. Con Vitamina E que humecta y cuida las pestañas.",
      price:10679
    },
    {
      id:9,
      image:,
      description:"Pestañina Poodle fórmula lavable,Cepillo perfecto para todo tipo de pestañas.",
      price:13569
    },
    {
      id:10,
      image:,
      description:"Pestañina Kraque, fórmulada en emulsión suave con los ojos, ligera, y cómoda al uso.",
      price:10256
    } 

  ],
  lipstick=[
    {
      id:1,
      image:,
      description:"Ruby rose batom liquido liquid matte lipstick",
      price:2000
    },
    {
      id:2,
      image:,
      description:"Vogue Cosméticos Labial Colorissimo Líquido Mate 5ml",
      price:17800
    },
    {
      id:3,
      image:,
      description:"",
      price:7560,

    },
    {
      id:4,
      image:,
      description:"",
      price:12589
    },
    {
      id:5,
      image:,
      description:"",
      price:9790
    },
    {
      id:6,
      image:,
      description:"",
      price:15600
    },
    {
      id:7,
      image:,
      description:"",
      price:3756
    },
    {
      id:8,
      image:,
      description:"",
      price:91679
    },
    {
      id:9,
      image:,
      description:"",
      price:1569
    },
    {
      id:10,
      image:,
      description:"",
      price:10256
    }  
  ],
  primers=[
    {
      id:1,
      image:,
      description:"",
      price:15000
    },
    {
      id:2,
      image:,
      description:,
      price:37800
    },
    {
      id:3,
      image:,
      description:,
      price:47560,

    },
    {
      id:4,
      image:,
      description:,
      price:22589
    },
    {
      id:5,
      image:,
      description:,
      price:2790
    },
    {
      id:6,
      image:,
      description:,
      price:25600
    },
    {
      id:7,
      image:,
      description:,
      price:8756
    },
    {
      id:8,
      image:,
      description:,
      price:11679
    },
    {
      id:9,
      image:,
      description:,
      price:2569
    },
    {
      id:10,
      image:,
      description:,
      price:11256
    } 
  ],
  iluminators=[
    {
      id:1,
      image:,
      description:"",
      price:15000
    },
    {
      id:2,
      image:,
      description:,
      price:37800
    },
    {
      id:3,
      image:,
      description:,
      price:47560,

    },
    {
      id:4,
      image:,
      description:,
      price:22589
    },
    {
      id:5,
      image:,
      description:,
      price:2790
    },
    {
      id:6,
      image:,
      description:,
      price:25600
    },
    {
      id:7,
      image:,
      description:,
      price:8756
    },
    {
      id:8,
      image:,
      description:,
      price:11679
    },
    {
      id:9,
      image:,
      description:,
      price:2569
    },
    {
      id:10,
      image:,
      description:,
      price:11256
    } 
  ],
  eyeShadows=[
    {
      id:1,
      image:,
      description:"",
      price:15000
    },
    {
      id:2,
      image:,
      description:,
      price:37800
    },
    {
      id:3,
      image:,
      description:,
      price:47560,

    },
    {
      id:4,
      image:,
      description:,
      price:22589
    },
    {
      id:5,
      image:,
      description:,
      price:2790
    },
    {
      id:6,
      image:,
      description:,
      price:25600
    },
    {
      id:7,
      image:,
      description:,
      price:8756
    },
    {
      id:8,
      image:,
      description:,
      price:11679
    },
    {
      id:9,
      image:,
      description:,
      price:2569
    },
    {
      id:10,
      image:,
      description:,
      price:11256
    } 
  ]
];
